- id: '1769903041530'
  alias: Motion Sensor Issy
  description: Motion detection in Issy
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: false
    webhook_id: MotionDetectionIssy
  conditions:
  - condition: state
    entity_id: switch.picam_issy_detection_de_mouvement_2
    state:
    - 'on'
  actions:
  - action: notify.envoi_mail
    metadata: {}
    data:
      message: Home Assistant a détecter des mouvement à Issy
      title: Home Assistant - Alerte Mouvement à Issy
      target: ph@schott.io
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: La caméra à détecter des mouvements à Issy. Vérifier les vidéos de
        sécurité!!
      title: Détection de mouvements à Issy
  mode: single
- id: '1769946336982'
  alias: Motion Sensor La Couture
  description: Motion detection in La Couture
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: false
    webhook_id: MotionDetectionLaCouture
  conditions:
  - condition: state
    entity_id: switch.picam_la_couture_detection_de_mouvement_2
    state:
    - 'on'
  actions:
  - action: notify.envoi_mail
    metadata: {}
    data:
      message: Home Assistant a détecter des mouvement à La Couture
      title: Home Assistant - Alerte Mouvement à La Couture
      target: ph@schott.io
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: La caméra à détecter des mouvements à La Couture. Vérifier les vidéos
        de sécurité!!
      title: Détection de mouvements à La Couture
  mode: single
- id: '1772007447556'
  alias: Tag entrée
  description: ''
  triggers:
  - trigger: tag
    tag_id: f260aca4-5cf2-4010-9e17-b40d107a9e2b
  - trigger: tag
    tag_id: 2c8edc63-7bc0-47e9-961e-44a3777a3dbd
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: light.lampe_entree
    data: {}
  mode: single
- id: '1772351581006'
  alias: MotionDetectionIssy2
  description: Motion detection in Issy
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: d358155ecf34704ee96f307966b7c6281bfa70b79152c2f635d9d7d05e79657f
  conditions:
  - condition: state
    entity_id: switch.picam_issy_detection_de_mouvement_2
    state:
    - 'on'
  actions:
  - action: notify.envoi_mail
    metadata: {}
    data:
      message: Home Assistant a détecter des mouvement à Issy
      title: Home Assistant - Alerte Mouvement à Issy
      target: ph@schott.io
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: La caméra à détecter des mouvements à Issy. Vérifier les vidéos de
        sécurité!!
      title: Détection de mouvements à Issy
  mode: single
- id: maj_options_voix_tts
  alias: MAJ options voix TTS depuis l'API
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  - hours: /6
    trigger: time_pattern
  conditions: []
  actions:
  - variables:
      voices: '{{ state_attr(''sensor.karotz_voice_list'',''voices'') | default([],
        true) }}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ voices | count > 0 }}'
      sequence:
      - target:
          entity_id: input_select.karotz_voice
        data:
          options: >
              {% set voices = state_attr('sensor.karotz_voice_list','voices') | default([], true) %}
              [
                {% for v in voices %}
                  "{{ v.id ~ ' - ' ~ v.lang }}"{% if not loop.last %},{% endif %}
                {% endfor %}
              ]
        action: input_select.set_options
  - target:
      entity_id: input_select.karotz_voice
    action: input_select.select_first
- id: maj_options_moods_tts
  alias: MAJ options Moods TTS depuis l'API
  description: ''
  triggers:
  - event: start
    trigger: homeassistant
  - hours: /6
    trigger: time_pattern
  conditions: []
  actions:
  - variables:
      moods: '{{ state_attr(''sensor.karotz_moods_list'',''moods'') | default([],
        true) }}'
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ moods | count > 0 }}'
      sequence:
      - target:
          entity_id: input_select.karotz_mood
        data:
          options: >
              {% set moods = state_attr('sensor.karotz_moods_list','moods') | default([], true) %}
              [
                {% for m in moods %}
                  "{{ m.id ~ ' - ' ~ (m.text
                                      | replace('&acirc;', 'â')
                                      | replace('&eacute;', 'é')
                                      | replace('&egrave;', 'è')
                                      | replace('&ccedil;', 'ç')
                                      | replace('&Ccedil;', 'Ç')
                                      | replace('&Ecirc;', 'Ê')
                                      | replace('&Eacute;', 'É')
                                      | replace('&agrave;', 'à')
                                      | replace('&ecirc;', 'ê')
                                      | replace('&icirc;', 'î')
                                      | replace('&ucirc;', 'û')
                                      | replace('&ugrave;', 'ù')
                                      | replace('&oelig;', 'œ')
                                      | replace('&ocirc;', 'ô')
                                      | replace('&hellip;', '...')
                                      | replace('&apos;', '\'')
                                      | replace('&rsquo;', '\'')
                                      ) }}"
                  {% if not loop.last %},{% endif %}
                {% endfor %}
              ]
        action: input_select.set_options
  - target:
      entity_id: input_select.karotz_mood
    action: input_select.select_first
